### ISSUE TITLE
Different widget behaviors when thousand separator is included/excluded in the product price

### ISSUE THREAD

**Issue by glennrocksvb** [sezzle/static-widgets#38]
When price amount is set to '**$3,291.20**' (with comma separator), the widget displays "or monthly payments as low as $603.33 with sezzle" and the modal displays NaN values for monthly and total.

![image](https://user-images.githubusercontent.com/30279453/111836516-a98c4d80-88b3-11eb-842f-709ce7c041c3.png)

When price amount is set to '**$3291.20**' (without comma separator), the widget displays "or monthly payments as low as $75.42 with sezzle" and the modal displays numeric values for monthly and total.

![image](https://user-images.githubusercontent.com/30279453/111836766-0ab42100-88b4-11eb-92ff-040a500ddb8b.png)

Which one should we use? Neither is completely correct. Although the second one seems more correct, it should at least display all the thousand values with thousand separator to make the amounts easily readable.

**Comment by glennrocksvb** [comment]
@aholdahl, thanks for fixing the issue. I can confirm it works.

But there are other minor things I observed. 😊

Can you please add the thousand separator back to the values when displaying them? I know you're stripping it off when you do the calculations but it would be nice to have the comma separator back when you display them for readability.

![image](https://user-images.githubusercontent.com/30279453/111851512-b0758900-88d0-11eb-926e-9070514c5013.png)

I also noticed that at 12px font-size for the Total amount and APR %, the custom font used seems to display funky alignment for the digit 9. Please see enlarged screenshot below for more details.

![image](https://user-images.githubusercontent.com/30279453/111851831-0434a200-88d2-11eb-8577-30e86e0a6df9.png)

Notice that 9's are not aligned with the other digits. If you change the font-size to 13px or 14px, the numbers get aligned properly.

Here's how it looks at font-size 13px.

![image](https://user-images.githubusercontent.com/30279453/111851953-79a07280-88d2-11eb-8688-cd7155b17882.png)

**Comment by aholdahl** [comment]
@glennrocksvb changes have been pushed for the thousandth delimiter and re-rendering the modal on alterPrice(). However, I am not having the issue with `9.99` that you have pictured. It is perplexing because the `.adjusted-total` is one string. I also see it happening on `.sample-apr` in your screenshot - could it be something picked up from your CSS?

**Comment by glennrocksvb** [comment]
Yeah it is one string. It's not a fault from the Sezzle widget code. It just seems to be how the custom font Comfortaa is rendering 9 at 12px.

I updated the jsfiddle https://jsfiddle.net/1beqy2nh/2/  (without your comma and modal fix yet) and the issue happens on my corporate computer that I'm connected to remotely but it works fine on my personal laptop at home. Could the issue be caused only by the Remote Desktop client?

Work computer: (issue occurs)
![image](https://user-images.githubusercontent.com/30279453/112030589-a71a3580-8af7-11eb-92f6-76ac687bfcd0.png)

Personal laptop: (looks good)
![image](https://user-images.githubusercontent.com/30279453/112031477-a0d88900-8af8-11eb-981b-c3b20d0be620.png)

**Comment by glennrocksvb** [comment]
Btw, I can confirm the comma fix in the modal works. But can you also please fix the same comma issue in the widget text?

![image](https://user-images.githubusercontent.com/30279453/112034537-d2068880-8afb-11eb-95d6-e7bdad946a78.png)

**Comment by aholdahl** [comment]
Comma separation in widget is now fixed as well. 

Can you confirm device, browser, and IP location for both computers?

**Comment by aholdahl** [comment]
@glennrocksvb I expanded font-family, let me know if it solves the issue, otherwise I can try bumping up the size as you mentioned earlier.

**Comment by glennrocksvb** [comment]
@aholdahl thanks for the font-family fix. I haven't tried it yet as I'm working on something else. I will get back to it and try before the end of day today. But looking at your change, I'm not sure if adding a fallback font-family would fix it. The main font Comfortaa is rendering so the added fallback font won't take effect.

**Comment by glennrocksvb** [comment]
@aholdahl , I can confirm that the fallback font solution doesn't fix the issue while accessing via Remote Desktop client. Since the issue seems to only occur using Remote Desktop though it could be also in combination with something else, this issue seems minor and may not be worth fixing unless someone else is able to reproduce the issue in normal scenario without remote connection.

**Comment by glennrocksvb** [comment]
> Comma separation in widget is now fixed as well.

I confirm that this fix works. Thanks!

**Comment by aholdahl** [comment]
> @aholdahl , I can confirm that the fallback font solution doesn't fix the issue while accessing via Remote Desktop client. Since the issue seems to only occur using Remote Desktop though it could be also in combination with something else, this issue seems minor and may not be worth fixing unless someone else is able to reproduce the issue in normal scenario without remote connection.

@glennrocksvb Does this mean I can close this issue?

**Comment by glennrocksvb** [comment]
Yes you can.

**Comment by glennrocksvb** [comment]
Just to add to this Comfortaa font alignment mystery...It seems the issue is not related to Remote Desktop client but to the extra monitor I'm using at home.

I load the Comfortaa font page at https://fonts.google.com/specimen/Comfortaa?preview.text_type=custom&preview.text=$3,619.99 and then change the font size in the dropdown to 12px.

"9" loads fine on my laptop screen. But when I dragged the same page to the other monitor, I see the alignment issue. My other monitor is a 27-inch curved monitor (Sceptre C27). Not sure if the issue occurs because the screen is curved and if it happens on all curved screens?

@aholdahl, can you try on your end if you happen to have a curved monitor?

**Comment by glennrocksvb** [comment]
@aholdahl I asked our dev team to test using that Comfortaa font page on Google and most devs encountered the same issue on curved monitors and some even on flat ones. One reported that on a curved monitor and a flat screen, Chromium Edge does not have that problem while Chrome does. One also reported not observing the issue on his 34-inch curved monitor.

It looks like increasing the `font-size` from `12px` to `13px` seem to fix the issue in most cases. Can you please do this fix?

Thanks!

**Comment by aholdahl** [comment]
Thanks Glenn - I was able to find some folks here with a curved monitor as well that were not having the issue. Such a strange issue, but the font-size has been bumped up now. Please keep me posted if there are any further issues.

**Comment by glennrocksvb** [comment]
@aholdahl thanks for the fix.
